// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {context} from '../models';
import {types} from '../models';

export function Start(arg1:context.Context):Promise<void>;

export function UploadData():Promise<types.JSResp>;
