// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function Start(arg1) {
  return window['go']['service']['checkInService']['Start'](arg1);
}

export function UploadData() {
  return window['go']['service']['checkInService']['UploadData']();
}
