// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function CheckInExcel(arg1, arg2, arg3) {
  return window['go']['service']['excelService']['CheckInExcel'](arg1, arg2, arg3);
}

export function Start(arg1) {
  return window['go']['service']['excelService']['Start'](arg1);
}
