// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {excel} from '../models';
import {types} from '../models';
import {context} from '../models';

export function CheckInExcel(arg1:string,arg2:Array<excel.CheckInData>,arg3:string):Promise<types.JSResp>;

export function Start(arg1:context.Context):Promise<void>;
