// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function Info() {
  return window['go']['service']['systemService']['Info']();
}

export function Latest() {
  return window['go']['service']['systemService']['Latest']();
}

export function Start(arg1, arg2) {
  return window['go']['service']['systemService']['Start'](arg1, arg2);
}
