// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function DoUpdate() {
  return window['go']['service']['updateService']['DoUpdate']();
}

export function Pause() {
  return window['go']['service']['updateService']['Pause']();
}

export function Start(arg1) {
  return window['go']['service']['updateService']['Start'](arg1);
}

export function Stop() {
  return window['go']['service']['updateService']['Stop']();
}
