// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {types} from '../models';
import {context} from '../models';

export function DoUpdate():Promise<types.JSResp>;

export function Pause():Promise<void>;

export function Start(arg1:context.Context):Promise<void>;

export function Stop():Promise<void>;
